name: Provision - BACKEND

on:
  workflow_dispatch:
    inputs:
      working-directory:
        required: true
        type: string
jobs:
  terraform:
    environment: ${{ inputs.environment }}

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login with Service Principal
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: 1.6.6
      #     terraform_wrapper: false

      # - name: Initialize Terraform with Azure Backend
      #   working-directory: ${{ inputs.working-directory }}
      #   run: |
      #     terraform init \
      #       -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
      #       -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
      #       -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
      #       -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
      #       -backend-config="access_key=${{ secrets.ACCESS_KEY }}"
